version: '3'

services:
  php:
    container_name: php
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - REDIS_HOST=redis
    entrypoint: sleep infinity
    volumes:
      - .:/app
  redis:
    container_name: redis
    image: redis:5.0.7
