version: '3'

services:
  redis-orm-php:
    container_name: redis-orm-php
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - REDIS_HOST=redis-orm-redis
    entrypoint: sleep infinity
    volumes:
      - .:/app
  redis-orm-redis:
    container_name: redis-orm-redis
    image: redis:5.0.7
